### PR TITLE
fix(translate): fix broken test

### LINKED ISSUE #543: rspec: Translate Quickstart translates Hello, world! to Russian failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: 67e1e4a540a6acd136ef54a2e4db5da31c3b7e1b
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/148d4a17-dc66-4eff-8da4-429166e65983), [Sponge](http://sponge2/148d4a17-dc66-4eff-8da4-429166e65983)
status: failed

### PR DESCRIPTION
**Pull request by tbpg**
Fixes #543.

### CODE REVIEW

File: translate/spec/quickstart_spec.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@
       load File.expand_path("../quickstart.rb", __dir__)
     }.to output(
       "Text: Hello, world!\n" +
-      "Translation: Привет, мир!\n"
+      "Translation: Привет мир!\n"
```
Comment (nnegrey) [inline translate/spec/quickstart_spec.rb:29]: Might be worth just switching to this for future changes. 
```suggestion
      "Translation:"
```

Comment (tbpg) [reply translate/spec/quickstart_spec.rb]: Done. Thanks!
