### PR TITLE
fix(spanner): list backups test

### LINKED ISSUE #796: rspec: Google Cloud Spanner API samples list backups with various filters failed
Note: #755 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 0f1c000e62f9f5a457f16b52784f887c1ba03741
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/dd8ec378-661a-458e-9948-b7977cb10cdf), [Sponge](http://sponge2/dd8ec378-661a-458e-9948-b7977cb10cdf)
status: failed
<details><summary>Test output</summary><br><pre>Failure/Error:
  expect(captured_output).to include(
    "All backups\n#{backup.backup_id}"
  )

  expected "All backups\ntest_bu_a38f75b97487de4b\ntest_bu_8b0f42761f7ae284\nAll backups with backup name contai...b0f42761f7ae284\nAll backups with pagination:\ntest_bu_a38f75b97487de4b\ntest_bu_8b0f42761f7ae284\n" to include "All backups\ntest_bu_8b0f42761f7ae284"
  Diff:
  @@ -1,17 +1,33 @@
  -All backups\ntest_bu_8b0f42761f7ae284
  +All backups
  +test_bu_a38f75b97487de4b
  +test_bu_8b0f42761f7ae284
  +All backups with backup name containing "test_bu_8b0f42761f7ae284":
  +test_bu_8b0f42761f7ae284
  +All backups for databases with a name containing "test_db_8b0f42761f7ae284":
  +test_bu_8b0f42761f7ae284
  +All backups that expire before a timestamp:
  +test_bu_a38f75b97487de4b
  +test_bu_8b0f42761f7ae284
  +All backups with a size greater than 500 bytes:
  +test_bu_8b0f42761f7ae284
  +All backups that were created after a timestamp that are also ready:
  +test_bu_8b0f42761f7ae284
  +All backups with pagination:
  +test_bu_a38f75b97487de4b
  +test_bu_8b0f42761f7ae284
./spec/spanner_samples_spec.rb:1680:in `block (2 levels) in <top (required)>'</pre></details>

### PR DESCRIPTION
**Pull request by jiren**
Fixes #796

### CODE REVIEW

File: spanner/spec/spanner_samples_spec.rb [hunk 1]
```diff
@@ -1677,26 +1677,36 @@ def capture
                    database_id: backup.database_id
     end
 
-    expect(captured_output).to include(
-      "All backups\n#{backup.backup_id}"
-    )
-    expect(captured_output).to include(
-      "All backups with backup name containing \"#{backup.backup_id}\":\n#{backup.backup_id}"
+    # Segregate each list operation output.
+    output_segements = captured_output.split(/(All backups)/)
```
Comment (hengfengli) [inline spanner/spec/spanner_samples_spec.rb:1681]: `output_segements` -> `output_segments`

**Review by hengfengli — APPROVED** [review]
Please fix the typo and then LGTM.
